### ISSUE TITLE
Indefinição de obrigatoriedade do campo "pagador" na criação do Pagamento

### ISSUE THREAD

**Issue by dgnunes** [bacen/pix-api-recebimentos#1]
Olá,

Lendo o Swagger com a definição da API de Recebimento, ficamos com uma dúvida:

- O campo pagador na rota "POST /document/" é mandatório ou não? A definição indica que caso o campo seja preenchido, os campos dos objetos PessoaFisica ou PessoaJuridica devem estar presentes. Porém não fica explícito se a presença em si desses objetos é obrigatória.

Obrigado.

**Comment by ninrod** [comment]
@dgnunes, bom dia. 

O campo `pagador` é opcional. Vamos deixar mais evidente essa questão na próxima release.

**Comment by dgnunes** [comment]
Obrigado!

**Comment by ninrod** [comment]
Vou tomar a liberdade de deixar essa issue aberta até que o problema seja resolvido por nós.

**Comment by ninrod** [comment]
consertado na `2.0.0`.

**Comment by dgnunes** [comment]
Alguma previsão de liberação da 2.0.0?

**Comment by ninrod** [comment]
@dgnunes estamos trabalhando para entregar até sexta dia 18.09.
