### ISSUE TITLE
[Dúvida] na [documentação] referente à [QR code] dinâmico

### ISSUE THREAD

**Issue by jocimarcan** [bacen/pix-api-recebimentos#10]
Prezados,
As dúvidas abaixo se referem às seguintes versões das documentações:
API de Recebimentos: 1.2.0
https://github.com/bacen/pix-api-recebimentos

Manual de padrões para iniciação do Pix: 1.0
https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II_ManualdePadroesparaIniciacaodoPix-versao1.pdf

Manual de segurança do Pix: 3.0
https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Manual%20de%20Seguranca%20do%20PIX%20v3.0.pdf

**Dúvidas**
Considerando o manual de iniciação do Pix, Pág. 12  
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/1.1.png)

e o endpoint POST /documento, como exemplo, da API de recebimentos
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/1.2.png) 
Pertunta-se:
**1) Porque o campo versão não está presente na resposta às chamadas dos endpoints?**
_________________________________________________________
Considerando o manual de iniciação do Pix, Pág. 14
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/2.1.png)
Pergunta-se:

**2) Qual método da API preenche o campo calendario.apresentacao? Em que momento ele é obrigatório e é preenchido?**
_________________
Considerando o manual de iniciação do Pix, Pág. 19
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/3.1.png)
Pergunta-se:
**3) A que método da API essa parte da documentação acredita estar chamando no HTTPS Request? Parece ser o método GET /documento/{txid}, mas esse método espera receber txid como parâmetro, e o que é passado acima parece ser o spiUrlToken 8b3da2f3-9a41-40d1-a91a-bd93113bd441. O formato da URL para Request, no exemplo, seria https://bx.com.br/pix/spiUrlToken/documento/{parâmetro}? Ou o spiUrlToken é que seria o identificador único do documento?**
__________________
Considerando o método POST da API recebimentos:
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/5.1.png)
Pergunta-se:

**4) Do que se trata realmente o payloadURL retornado pelo POST /documento? Ele é o link de pagamento ou a URL do payload? “123” seria o spiUrlToken? O formato https://pix.example.com/qr/ do retorno da API, diferente do formato https://bx.com.br/pix/ do Manual de iniciação do Pix, me gerou essa dúvida da real intenção nesse retorno da API.**
______________________________
Também referente à API de recebimentos:
**5) Quais endpoints devem ser expostos para outros PSPs?** 
_____________
**6) As devoluções se referem apenas às devoluções de recebimentos feitos por QR code dinâmico. Certo?**
_______________
**7) Quando será lançada a nova versão da API de recebimentos?**
______________
**8) Haverá algum marco homologatório para QR code dinâmico? A funcionalidade de QR code dinâmico ainda continua obrigatória para novembro? Há algum cronograma?**
__________________
Conforme Manual de segurança, Pág 28:
![](https://raw.githubusercontent.com/jocimarcan/duvidasBacen/master/10.1.png)
Pergunta-se:
**9) Qual o formato e layout desse arquivo? Minha dúvida é se será necessário ler todos os campos CN ou SAN dos certificados de todos os PSPs a cada leitura de QR code, a fim de validar a URL do site/domínio de QR Code dinâmico.**

**Comment by ninrod** [comment]
prezado @jocimarcan 

> 1) Porque o campo versão não está presente na resposta às chamadas dos endpoints?

Porque esse campo versão diz respeito ao payload JSON retornado pelo PSP recebedor no momento do scan do QR Code pelo app do PSP pagador. 

Um esquema de versionamento da API de recebimentos está previsto para a versão `2.0.0`. 

```sh
# por exemplo
PUT https://psp.com.br/pix/api/v1/documento/{txid}
```


> 2) Qual método da API preenche o campo calendario.apresentacao? Em que momento ele é obrigatório e é preenchido?

O `calendario.criacao` é de responsabilidade do PSP recebedor. É apenas retornado ao usuário recebedor. 

> 3) A que método da API essa parte da documentação acredita estar chamando no HTTPS Request? Parece ser o método GET /documento/{txid}, mas esse método espera receber txid como parâmetro, e o que é passado acima parece ser o spiUrlToken 8b3da2f3-9a41-40d1-a91a-bd93113bd441. O formato da URL para Request, no exemplo, seria https://bx.com.br/pix/spiUrlToken/documento/{parâmetro}? Ou o spiUrlToken é que seria o identificador único do documento?

Trata-se do endpoint que serve o payload JSON que representa a cobrança. Responsabilidade do PSP recebedor. 

> 4) Do que se trata realmente o payloadURL retornado pelo POST /documento? Ele é o link de pagamento ou a URL do payload? “123” seria o spiUrlToken? O formato https://pix.example.com/qr/ do retorno da API, diferente do formato https://bx.com.br/pix/ do Manual de iniciação do Pix, me gerou essa dúvida da real intenção nesse retorno da API.**

Nosso exemplo atrapalhou aqui. Será consertado na versão 2.0.0 Trata-se do spiUrlToken. Esse é o endpoint que serve o payload JSON que é retornado pelo PSP recebedor quando o app do PSP pagador realiza o scan do QR Code. 


> 5) Quais endpoints devem ser expostos para outros PSPs?

Os endpoints deve ser expostos para os clientes do PSP em questão que estejam habilitados a operar a API de recebimentos. 

> 6) As devoluções se referem apenas às devoluções de recebimentos feitos por QR code dinâmico. Certo?

Por QR Estático também, no caso de haver um `txid` associado. Um PIX atrelado a um `{txid}` será objeto de listagem na API de recebimentos. 

> 7) Quando será lançada a nova versão da API de recebimentos?

Complicado colocar uma data precisa. Posso adiantar que estamos trabalhando para liberar uma versão ainda esse mês. 

> 8) Haverá algum marco homologatório para QR code dinâmico? A funcionalidade de QR code dinâmico ainda continua obrigatória para novembro? Há algum cronograma?**

Ainda não está previsto um marco homologatório para QR Dinâmico. O QR Dinâmico não é obrigatório. A API de recebimentos também não é obrigatória. Não há cronograma definido, nesse momento, para a API de recebimentos, no contexto de implementação por parte dos PSPs. 

> 9) Qual o formato e layout desse arquivo? Minha dúvida é se será necessário ler todos os campos CN ou SAN dos certificados de todos os PSPs a cada leitura de QR code, a fim de validar a URL do site/domínio de QR Code dinâmico.

O BC ainda não iniciou a recepção de arquivos de certificados do tipo CERTQRC, mas após a recepção de arquivos desse tipo ser iniciada, o download do arquivo com todos os certificados CERTQRC dos PSPs não será realizado via STA, mas sim por meio da interface ARQ, conforme seção 4 do Manual das Interfaces de Comunicação, disponível em https://www.bcb.gov.br/estabilidadefinanceira/comunicacaodados.


@jocimarcan , suas dúvidas foram respondidas, considerando as respostas acima destacadas?

**Comment by jocimarcan** [comment]
Obrigado @ninrod pela rapidez e pelas respostas a cada item. A maioria das dúvidas foram perfeitamente respondidas.
Há ainda alguns pontos que me parecem obscuros, mas acredito que vocês deixarão as coisas mais claras na próxima versão.
Qualquer coisa, criarei outra issue
