### ISSUE TITLE
QR Code Dinâmico: URL - spiUrlAccessToken

### ISSUE THREAD

**Issue by mbenatti** [bacen/pix-api-recebimentos#11]
### Segundo a documentação:
Respeitadas as regras de formação de URL, a URL terá esse layout:
fqdnPspRecebedor/spiEndpoint/spiUrlAccessToken/
O também é requisito UUID v4() no caso do uso de UUID.

No documento não está claro se o `spiUrlAccessToken` será `único` por revisão ou por documento, ou seja, terá uma URL única para para cada revisão.
Também não está claro se pode/deve ser usado o ID do documento/qr_code_payload no campo `spiUrlAccessToken`

### Dúvidas:

 1) A URL será a representação de um único documento, sempre retornando a versão mais recente do documento/payload_qr_code ou terá uma URL para cada revisão?(se sim deveriamos invalidar as URLs de revisões antigas certo?)

 2) No caso da URL ser única por documento, teria algum problema em usar o ID do documento/qr_code_payload no campo `spiUrlAccessToken` ? Isso é indiferente e fica a cargo do PSP decidir?

3) Dado um request de link / qr code dinâmico:
```
HTTPS Request:
https://bx.com.br/pix/8b3da2f3-9a41-40d1-a91a-bd93113bd441
HTTPS Response:
JWSHeader.JWSPayload.JWSSignature
```

Qual será o mine type usado na resposta contendo o `JWS`? `text/plain` ou outro?

**Comment by ninrod** [comment]
> 1. A URL será a representação de um único documento, sempre retornando a versão mais recente do documento/payload_qr_code ou terá uma URL para cada revisão?(se sim deveriamos invalidar as URLs de revisões antigas certo?)

Não necessariamente a URL representa um "único documento". Pense na URL como uma vitrine, que pode mostrar um determinado payload em um determinado momento na linha do tempo. Ficará mais claro na versão `2.0.0` da api, a ser liberada "em breve". 

> 2. No caso da URL ser única por documento, teria algum problema em usar o ID do documento/qr_code_payload no campo spiUrlAccessToken ? Isso é indiferente e fica a cargo do PSP decidir?

Não é o caso.

> 3. Dado um request de link / qr code dinâmico:

``` http
HTTPS Request:
https://bx.com.br/pix/8b3da2f3-9a41-40d1-a91a-bd93113bd441
HTTPS Response:
JWSHeader.JWSPayload.JWSSignature
```

> Qual será o mine type usado na resposta contendo o JWS? text/plain ou outro?

R: Conforme consta na RFC 7515, seção [9.2.1](https://tools.ietf.org/html/rfc7515#section-9.2.1), o MIME Type correto neste caso seria o `application/jose`.
