### ISSUE TITLE
TxID - PACS008

### ISSUE THREAD

**Issue by b-alencar** [bacen/pix-api-recebimentos#13]
Tenho uma duvida referente a APIREC versus o TxID trafegado na PACS008. 
No manual é citado que: "Inserção manual dos dados pelo usuário pagador: a transferência manual é iniciada pelo PSP do pagador. O txid, portanto, nesse caso, é escolhido pelo usuário pagador. "
Dado a informação acima, gostaria de apresentar o seguinte cenário. 
O recebedor João emite um QR Code dinâmico com o txid - XPTO no banco X e o pagador Maria envia uma inserção manual através do banco Y para o Joao também com o txid XPTO. 
No envio dessas informações entre os bancos os dados trafegados serão agencia, conta, valor e txid em ambas as situações. Ou seja, nessa situação como será validado que se trata de um QR Code ou de uma inserção manual?

**Comment by ninrod** [comment]
@b-alencar, obrigado pela contribuição. Informo essa redação será alterada muito em breve. 

Adianto que não há mais essa possibilidade de inserção do txid no fluxo manual. 

E o txid passará a ser responsabilidade do usuário recebedor, na API PIX. (de API de recebimentos, passará a chamar-se API PIX).

**Comment by b-alencar** [comment]
Muito obrigada pelo retorno, mas, ainda assim temos txid sendo trafegado através do QRCode estatico. Como será tratado o estatico? Ele deverá ser unico entre QRCode dinamico, estatico e por CPF/CNPJ? Se sim, a API PIX será direcionada aos dois tipos de QR Codes e não mais apenas ao dinamico?

**Comment by ninrod** [comment]
Olá @b-alencar . 

o txid é único por CPF/CNPJ do usuário recebedor. O txid está sob a responsabilidade do usuário recebedor. 

no caso de "acidentalmente" o QR estático conter o mesmo txid que um QR dinâmico, na prática, o que irá acontecer depender das validações do psp recebedor; 

- o PSP recebedor pode rejeitar um pix associado a um txid que não esteja em conformidade com o valor, por exemplo. 
- se o PSP recebedor não rejeitar porque, por exemplo, o valor bate, na prática, o que vai acontecer é que se você consultar a cobrança, 2 pix estarão associados a ela: um pix realizado via QR Estático, e um pix iniciado via QR dinâmico.
