### ISSUE TITLE
[Sugestão] - Paginação na API - Recuperar lista de documentos.

### ISSUE THREAD

**Issue by oximer** [bacen/pix-api-recebimentos#2]
Não seria adequado utilizarmos para a API de Recuperar Lista de documentos, um modelo de paginação já bastante testado e robusto?

Conforme descrito no blog de engenharia do Twitter, eles apresentam problemas para montar timeline dos usuários e resolveram criando um modelo de listagem baseando em cursor ou em parâmetros (since_id e max_id).

https://developer.twitter.com/en/docs/tweets/timelines/guides/working-with-timelines
https://developer.twitter.com/en/docs/basics/cursoring

O modelo de cursor também é utilizado pelo Facebook.

https://developers.facebook.com/docs/graph-api/using-graph-api/#cursors

`
Cursor-based pagination is the most efficient method of paging and should always be used when possible. A cursor refers to a random string of characters which marks a specific item in a list of data. The cursor will always point to the item, however it will be invalidated if the item is deleted or removed. Therefore, your app shouldn't store cursors or assume that they will be valid in the future.
`

Esse artigo sumariza algumas das abordagens que considero comprovadamente efetivas de paginação

https://www.sitepoint.com/paginating-real-time-data-cursor-based-pagination/

**Comment by ninrod** [comment]
@oximer , obrigado pelas referências. 

Na `2.0.0` acredito que vamos optar por "time-based".
