### ISSUE TITLE
Get Documentos ser especifica e não genérica

### ISSUE THREAD

**Issue by leosn** [bacen/pix-api-recebimentos#3]
A API GET documentos, pelo que entendemos, retorna vários tipo de documentos (pagamentos, devoluções, QR-Codes). Acreditamos que essa consulta, principalmente para  clientes com grandes movimentações (principalmente PJ),  poderá ser bem dispendiosa para o PSP. Sugerimos uma consulta específica para cada tipo de documento. Concordamos também com consultas com paginação por cursor como outro colega sugeriu.

**Comment by ninrod** [comment]
@leosn, a devolução faz parte de um documento de cobrança, assim como os pagamentos recebidos para honrar uma cobrança. 

Para evitar de ter que retornar uma quantidade enorme de registros, entendemos que a paginação deve ser bem desenhada. Vamos avaliar sim a paginação por cursores, então vou fechar essa issue e continuamos a discussão em #2.
