### ISSUE TITLE
Dúvida StatusDocumento e StatusDevolução

### ISSUE THREAD

**Issue by coliveira-thiago** [bacen/pix-api-recebimentos#4]
https://github.com/bacen/pix-api-recebimentos/blob/00d100ee9c8c1d6fda6c483eab5b7f935783b0b3/openapi.yaml#L398

Gostaria de saber quando serão utilizados os status "a_devolver", "completamente_devolvido", "parcialmente_devolvido". Pois eu imaginava que seriam utilizados da forma abaixo: 

"a_devolver" => alguma devolução em andamento
"parcialmente_devolvido" => alguma devolução aprovada
"completamente_devolvido" => todas as devoluções aprovadas

Porém ao olhar os exemplos, existe um retorno de consulta onde haviam devoluções pendente e aprovada, porém o status continuava como "pago".

https://github.com/bacen/pix-api-recebimentos/blob/00d100ee9c8c1d6fda6c483eab5b7f935783b0b3/openapi.yaml#L588

Gostaria de saber também se não teremos o status "negado" para uma devolução.

**Comment by ninrod** [comment]
Perfeito @coliveira-thiago, estamos reunindo os feedbacks em cima da versão 1.2.0 e devemos soltar uma nova versão em breve. 

Essa questão que você levantou será levada em consideração. .

**Comment by ninrod** [comment]
@coliveira-thiago , consertado na `2.0.0` que será lançada em breve.
