### ISSUE TITLE
SPEC com referencia desconhecida

### ISSUE THREAD

**Issue by leonardoderoldo** [bacen/pix-api-recebimentos#5]
Ao importar o spec.yaml,  percebi que a classe(ConfigApi) gerada apresentou problema quando tenta fazer um import 
e referencias nos métodos. A versão usada foi a 1.2.0

import XXX.pix.qrcode.api.model.UNKNOWN_BASE_TYPE;

    /**
     * Criar documento.
     *
     * Cria um novo payload JSON representando um QR/Link dinâmico.
     *
     */
    @POST
    @Path("/documento/")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "Criar documento.", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Documento gerado.", response = DocumentoGerado.class) })
    public Response documentoPost(**UNKNOWN_BASE_TYPE** UNKNOWN_BASE_TYPE);

  /**
     * Alterar documento.
     *
     * Altera um payload JSON que representa um QR/Link dinâmico.
     *
     */
    @PUT
    @Path("/documento/{txid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "Alterar documento.", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Documento alterado. O campo <i>payloadURL</i> é igual ao de criação. A revisão deve ser incrementada.", response = DocumentoGerado.class) })
    public Response documentoTxidPut(@PathParam("txid") String txid, **UNKNOWN_BASE_TYPE** **UNKNOWN_BASE_TYPE**);

**Comment by ninrod** [comment]
@leonardoderoldo , obrigado. 

Vou marcar como bug.

**Comment by ninrod** [comment]
@leonardoderoldo , consertado na `2.0.0`, que será lançada em breve.
