### ISSUE TITLE
txId é unico na plataforma?

### ISSUE THREAD

**Issue by mvallim** [bacen/pix-api-recebimentos#6]
Olá,

Se a consulta de um documento é pelo txId, como isso seria tratado quando os participantes indiretos e os clientes informam o mesmo txId.

Exemplo:
- joão cadastra `txId` = `1234`
- maria cadastra `txId` = `1234`

Quando os dois fazem a busca pelo documento usando o txId como é identidicado o txId de um ou do outro?

Olhando a [spec](https://github.com/bacen/pix-api-recebimentos/blob/00d100ee9c8c1d6fda6c483eab5b7f935783b0b3/openapi.yaml#L140) não tem nenhuma outra informação que identifica unicamente um ou outro.

**Comment by ninrod** [comment]
@mvallim 

> Quando os dois fazem a busca pelo documento usando o txId como é identidicado o txId de um ou do outro?

Entendo que, no cenário proposto, joão e maria estejam acessando a API de um mesmo PSP. 

O  `1234` do joão é diferente do `1234` da maria porque joão e maria estão em "diferentes caixas" dentro da API do recebedor. 

Sem querer simplificar demais o cenário, imagine que o PSP do recebedor consiga identificar joão e maria por meio de suas credenciais. O PSP do recebedor pode associar então, ao txid `1234` de joão, o seu clientId. 

O pares `(clientIdDeJoao, 1234)` e `(clientIdDeMaria, 1234)` sempre serão diferentes.
