### ISSUE TITLE
[Curiosidade] Representação de valores na API

### ISSUE THREAD

**Issue by christianf2029** [bacen/pix-api-recebimentos#9]
A representação atual de campos numéricos reais / ponto flutuante, seja para valores financeiros ou para outras finalidades (como o campo `juros`), está no padrão `\d{10}.\d{2}` ou `[0-9]{10}.[0-9]{2}`. 

Isso segue alguma normativa do BC, ou alguma outra regulamentação, ou foi acordado entre os PSPs, ou ainda está em aberto?

Digo isso porque **acredito** que a representação em centavos, diretamente como numérico inteiro e sem o digito separador `.`, é mais simples de ser convertida e manipulada durante todo o fluxo de troca, cálculo e armazenamento de informações.

**Comment by ninrod** [comment]
Prezado @christianf2029, 

Essa regex tenta seguir a especificação EMV para QR Codes, especificamente "EMV® QR Code Specification for Payment Systems: Merchant-Presented Mode", que você pode encontrar em inteiro teor __[aqui](https://www.emvco.com/emv-technologies/qrcodes/)__. 

A versão corrente do documento é a v1.1. Na seção 4.7.4.1, que trata sobre o  "Transaction Amount (ID "54")", você encontra esse padrão para representar os valores.
